export default {
  GET_MOVIES_LIST_START: "GET_MOVIES_LIST_START",
  SCROLL_GET_MOVIES_LIST_START: "SCROLL_GET_MOVIES_LIST_START",
  GET_MOVIES_LIST_SUCCESS: "GET_MOVIES_LIST_SUCCESS",
  SCROLL_GET_MOVIES_LIST_SUCCESS: "SCROLL_GET_MOVIES_LIST_SUCCESS",
  CLEAR_MOVIES_LIST: "CLEAR_MOVIES_LIST",
  GET_STARTER_MOVIE_SUCCESS: "GET_STARTER_MOVIE_SUCCESS",
  GET_MOVIE_DETAILS_START: "GET_MOVIE_DETAILS_START",
  GET_MOVIE_DETAILS_SUCCESS: "GET_MOVIE_DETAILS_SUCCESS",
};
